DATA_DIR = '../data'


STOP_WORDS = {'around', 'namely', 'against', 'front', 'only',
              'third', 'very', 'however', 'again', 'top', 'until', 'hundred',
              'between', 'towards', 'meanwhile', 'always', 'mostly', 'should',
              'regarding', 'cannot', 'such', 'where', 'a', 'own', 'put',
              'wherein', 'forty', 'whereupon', 'yourself', 'besides', 'alone',
              'can', 'there', 'herself', 'much', 'never', 'whether', 'with',
              'therein', 'his', 'into', 'has', 'rather', 'nowhere', 'although',
              'itself', 'those', 'throughout', 'its', 'in', 'less', 'then',
              'whom', 'is', 'therefore', 'this', 'yourselves', 'both', 'almost',
              'four', 'inc', 'anyhow', 'hereby', 'ten', 'ca', 'ourselves', 'the',
              'these', 'who', 'becoming', 'thereafter', 'could', 'been', 'that',
              'us', 'take', 'because', 'thence', 'even', 'together', 'whither',
              'etc', 'several', 'your', 'give', 'side', 'we', 'back', 'become',
              'being', 'empty', 'among', 'afterwards', 'be', 'across', 'already',
              'he', 'next', 'whoever', 'unless', 'last', 'used', 'full', 'what',
              'above', 'their', 'latterly', 'also', 'did', 'noone', 'else',
              'elsewhere', 'name', 'former', 'by', 'fifteen', 'beforehand',
              'serious', 'have', 'seemed', 'everywhere', 'five', 'six', 'each',
              'as', 'so', 'anything', 'someone', 'see', 'one', 'himself',
              'about', 'must', 'ever', 'during', 'nobody', 'whose', 'on', 'from',
              'two', 'was', 'onto', 'yet', 'since', 'am', 'many', 'whereafter',
              'using', 'though', 'thus', 'whole', 'all', 'our', 're', 'per',
              'once', 'it', 'might', 'over', 'became', 'seems', 'to', 'which',
              'formerly', 'just', 'ours', 'below', 'amongst', 'would', 'due',
              'now', 'behind', 'really', 'further', 'becomes', 'make', 'enough',
              'for', 'please', 'amount', 'fifty', 'if', 'along', 'myself',
              'and', 'were', 'after', 'move', 'still', 'well', 'him', 'twelve',
              'neither', 'thereby', 'wherever', 'they', 'anyone', 'me', 'few',
              'more', 'sixty', 'latter', 'through', 'keep', 'seeming',
              'anywhere', 'of', 'when', 'you', 'doing', 'bottom', 'either',
              'does', 'off', 'somehow', 'others', 'at', 'mine', 'beside',
              'down', 'indeed', 'eleven', 'everyone', 'whenever', 'often',
              'nevertheless', 'an', 'any', 'while', 'thru', 'go', 'will',
              'except', 'some', 'too', 'them', 'her', 'three', 'most',
              'nothing', 'or', 'show', 'do', 'twenty', 'nor', 'had', 'various',
              'least', 'within', 'she', 'why', 'say', 'without', 'somewhere',
              'yours', 'anyway', 'i', 'toward', 'something', 'before', 'beyond',
              'themselves', 'via', 'eight', 'whereby', 'than', 'thereupon',
              'my', 'sometime', 'get', 'quite', 'made', 'no', 'whereas', 'may',
              'part', 'herein', 'sometimes', 'out', 'another', 'whatever',
              'here', 'moreover', 'upon', 'but', 'call', 'same', 'perhaps',
              'seem', 'under', 'are', 'done', 'how', 'not', 'otherwise', 'hers',
              'none', 'hereupon', 'other', 'hence', 'up', 'whence', 'first',
              'every', 'nine', 'hereafter', 'everything'}
